<?php

declare(strict_types=1);

namespace Coffesoft\LaravelBeacon\Intelligence;

/**
 * Generates ai-summary.md — an LLM-optimized file where every important class
 * has a concise summary in the format:
 *
 * # ClassName
 *
 * Purpose: ...
 * Responsibilities: ...
 * Uses: ...
 * Routes: ...
 * Business Rules: ...
 * Possible Impact: ...
 *
 * No code duplication. Max 15 lines per summary.
 */
class AiSummaryEngine
{
    /**
     * @param array<string, mixed> $data All scanned project data
     * @return array<string, mixed>
     */
    public function generate(array $data): array
    {
        $lines = [];

        $lines[] = '# AI Summary — ' . basename(base_path());
        $lines[] = '';
        $lines[] = '> LLM-optimized class summaries for AI-assisted development.';
        $lines[] = '> Every important class has a concise summary below.';
        $lines[] = '> Confidence scores (0–100) indicate reliability.';
        $lines[] = '> Generated by Laravel Beacon v5';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        // Summarize models
        foreach ($data['models']['items'] ?? [] as $model) {
            $lines[] = $this->summarizeModel($model, $data);
            $lines[] = '';
        }

        // Summarize controllers
        foreach ($data['controllers']['items'] ?? [] as $ctrl) {
            $lines[] = $this->summarizeController($ctrl, $data);
            $lines[] = '';
        }

        // Summarize services
        foreach ($data['services']['items'] ?? [] as $svc) {
            $lines[] = $this->summarizeService($svc, $data);
            $lines[] = '';
        }

        // Summarize repositories
        foreach ($data['repositories']['items'] ?? [] as $repo) {
            $lines[] = $this->summarizeRepository($repo, $data);
            $lines[] = '';
        }

        // Summarize form requests
        foreach ($data['form_requests']['items'] ?? [] as $req) {
            $lines[] = $this->summarizeRequest($req);
            $lines[] = '';
        }

        // Summarize policies
        foreach ($data['policies']['items'] ?? [] as $policy) {
            $lines[] = $this->summarizePolicy($policy);
            $lines[] = '';
        }

        // Summarize events
        foreach ($data['events']['items'] ?? [] as $event) {
            $lines[] = $this->summarizeEvent($event);
            $lines[] = '';
        }

        // Summarize jobs
        foreach ($data['jobs']['items'] ?? [] as $job) {
            $lines[] = $this->summarizeJob($job);
            $lines[] = '';
        }

        // Summarize notifications
        foreach ($data['notifications']['items'] ?? [] as $notif) {
            $lines[] = $this->summarizeNotification($notif);
            $lines[] = '';
        }

        // Summarize Livewire components
        foreach ($data['livewire']['components'] ?? [] as $lw) {
            $lines[] = $this->summarizeLivewire($lw);
            $lines[] = '';
        }

        return [
            'ai_summary' => [
                'content' => implode("\n", $lines),
                'line_count' => substr_count(implode("\n", $lines), "\n") + 1,
                'confidence' => 85,
            ],
        ];
    }

    private function summarizeModel(array $model, array $data): string
    {
        $lines = [];
        $lines[] = "# {$model['name']}";
        $lines[] = '';
        $lines[] = "**Type:** Model | **Namespace:** `{$model['namespace']}` | **File:** `{$model['path']}`";
        $lines[] = "**Confidence:** 90";
        $lines[] = '';

        $fillable = $model['fillable'] ?? [];
        $casts = $model['casts'] ?? [];
        $traits = $model['traits'] ?? [];
        $relations = $model['relations'] ?? [];
        $scopes = $model['scopes'] ?? [];
        $accessors = $model['accessors'] ?? [];

        $lines[] = "**Purpose:** Represents the '{$model['name']}' entity in the database.";

        if (!empty($fillable)) {
            $lines[] = "**Attributes:** " . implode(', ', $fillable);
        }
        if (!empty($casts)) {
            $castStr = implode(', ', array_map(fn($k, $v) => "{$k} => {$v}", array_keys($casts), $casts));
            $lines[] = "**Casts:** {$castStr}";
        }
        if (!empty($traits)) {
            $lines[] = "**Traits:** " . implode(', ', $traits);
        }
        if (!empty($relations)) {
            $relStr = [];
            foreach ($relations as $rel) {
                $relType = $rel['type'] ?? 'unknown';
                $relTarget = $rel['target'] ?? 'unknown';
                $relStr[] = "{$relType} -> {$relTarget}";
            }
            $lines[] = "**Relationships:** " . implode(', ', $relStr);
        }
        if (!empty($scopes)) {
            $lines[] = "**Scopes:** " . implode(', ', $scopes);
        }
        if (!empty($accessors)) {
            $lines[] = "**Accessors:** " . implode(', ', $accessors);
        }

        // Impact info
        $impacts = [];
        foreach ($data['controllers']['items'] ?? [] as $ctrl) {
            if (preg_replace('/Controller$/', '', $ctrl['name']) === $model['name']) {
                $impacts[] = $ctrl['name'];
            }
        }
        foreach ($data['services']['items'] ?? [] as $svc) {
            foreach ($svc['referenced_models'] ?? [] as $ref) {
                if (str_contains($ref, "\\{$model['name']}")) {
                    $impacts[] = $svc['name'];
                    break;
                }
            }
        }
        if (!empty($impacts)) {
            $lines[] = "**Used By:** " . implode(', ', array_unique($impacts));
        }
        $lines[] = "**Possible Impact:** Editing this model affects " . (count($impacts) ?: 'no') . " other classes.";

        return implode("\n", $lines);
    }

    private function summarizeController(array $ctrl, array $data): string
    {
        $lines = [];
        $name = $ctrl['name'];
        $lines[] = "# {$name}";
        $lines[] = '';
        $lines[] = "**Type:** Controller | **Namespace:** `{$ctrl['namespace']}` | **File:** `{$ctrl['path']}`";
        $lines[] = "**Confidence:** 90";
        $lines[] = '';

        $methods = $ctrl['methods'] ?? [];
        $middleware = $ctrl['middleware'] ?? [];
        $group = $ctrl['group'] ?? '';
        $isCrud = $ctrl['is_crud'] ?? false;

        if ($isCrud) {
            $modelName = preg_replace('/Controller$/', '', $name);
            $lines[] = "**Purpose:** Manage {$modelName} entities with full CRUD operations.";
        } else {
            $lines[] = "**Purpose:** Handle HTTP requests in the `{$group}` group.";
        }

        $lines[] = "**Responsibilities:**";
        foreach ($methods as $m) {
            $lines[] = "- `{$m}()` — " . $this->describeMethod($m, $name);
        }

        if (!empty($middleware)) {
            $lines[] = "**Middleware:** " . implode(', ', $middleware);
        }

        // Find routes
        $routes = array_filter($data['routes']['items'] ?? [], fn($r) =>
            str_contains($r['action'] ?? '', "\\{$name}@") || str_contains($r['action'] ?? '', "{$name}@")
        );
        if (!empty($routes)) {
            $lines[] = "**Routes (" . count($routes) . "):**";
            foreach ($routes as $r) {
                $methods = implode('/', array_diff($r['methods'] ?? [], ['HEAD']));
                $lines[] = "- `{$methods}` `{$r['uri']}`";
            }
        }

        // Impact
        $impact = [];
        if ($serviceName = $this->findServiceForController($name, $data)) {
            $impact[] = $serviceName;
        }
        if ($requestName = $this->findRequestForController($name, $data)) {
            $impact[] = $requestName;
        }
        if (!empty($impact)) {
            $lines[] = "**Uses:** " . implode(', ', $impact);
        }

        return implode("\n", $lines);
    }

    private function summarizeService(array $svc, array $data): string
    {
        $lines = [];
        $name = $svc['name'];
        $lines[] = "# {$name}";
        $lines[] = '';
        $lines[] = "**Type:** " . ($svc['type'] ?? 'Service') . " | **Namespace:** `{$svc['namespace']}` | **File:** `{$svc['path']}`";
        $lines[] = "**Confidence:** 85";
        $lines[] = '';

        $methods = $svc['methods'] ?? [];
        $deps = $svc['dependencies'] ?? [];
        $models = $svc['referenced_models'] ?? [];
        $repos = $svc['referenced_repositories'] ?? [];
        $jobs = $svc['referenced_jobs'] ?? [];
        $events = $svc['referenced_events'] ?? [];
        $notifs = $svc['referenced_notifications'] ?? [];
        $responsibilities = $svc['responsibilities'] ?? [];

        $lines[] = "**Purpose:** Encapsulates business logic for the domain.";

        if (!empty($responsibilities)) {
            $lines[] = "**Responsibilities:** " . implode(', ', $responsibilities);
        }

        $lines[] = "**Methods (" . count($methods) . "):** " . implode(', ', $methods);

        if (!empty($deps)) {
            $depStrs = array_map(fn($d) => ($d['type'] ?? '?') . ' $' . $d['name'], $deps);
            $lines[] = "**Injected Dependencies:** " . implode(', ', $depStrs);
        }

        if (!empty($models)) {
            $modelNames = array_map(fn($m) => substr(strrchr($m, '\\') ?: $m, 1), $models);
            $lines[] = "**Uses Models:** " . implode(', ', $modelNames);
        }
        if (!empty($repos)) {
            $repoNames = array_map(fn($r) => substr(strrchr($r, '\\') ?: $r, 1), $repos);
            $lines[] = "**Uses Repositories:** " . implode(', ', $repoNames);
        }
        if (!empty($jobs)) {
            $jobNames = array_map(fn($j) => substr(strrchr($j, '\\') ?: $j, 1), $jobs);
            $lines[] = "**Dispatches Jobs:** " . implode(', ', $jobNames);
        }
        if (!empty($events)) {
            $eventNames = array_map(fn($e) => substr(strrchr($e, '\\') ?: $e, 1), $events);
            $lines[] = "**Dispatches Events:** " . implode(', ', $eventNames);
        }

        return implode("\n", $lines);
    }

    private function summarizeRepository(array $repo, array $data): string
    {
        $lines = [];
        $name = $repo['name'];
        $lines[] = "# {$name}";
        $lines[] = '';
        $lines[] = "**Type:** Repository | **Namespace:** `{$repo['namespace']}` | **File:** `{$repo['path']}`";
        $lines[] = "**Confidence:** 85";
        $lines[] = '';

        $models = $repo['referenced_models'] ?? [];
        $methods = $repo['methods'] ?? [];

        $lines[] = "**Purpose:** Data access layer for database operations.";

        if (!empty($models)) {
            $modelNames = array_map(fn($m) => substr(strrchr($m, '\\') ?: $m, 1), $models);
            $lines[] = "**Works With Models:** " . implode(', ', $modelNames);
        }
        $lines[] = "**Methods (" . count($methods) . "):** " . implode(', ', $methods);

        return implode("\n", $lines);
    }

    private function summarizeRequest(array $req): string
    {
        $lines = [];
        $name = $req['name'];
        $rules = $req['rules'] ?? [];

        $lines[] = "# {$name}";
        $lines[] = '';
        $lines[] = "**Type:** Form Request | **File:** `{$req['path']}`";
        $lines[] = "**Confidence:** 90";
        $lines[] = '';

        $lines[] = "**Purpose:** Validates incoming HTTP request data.";
        $lines[] = "**Rules:** " . count($rules) . " fields validated.";
        if (!empty($rules)) {
            $lines[] = "**Fields:** " . implode(', ', array_map(fn($r) => $r['field'], array_slice($rules, 0, 8))) . (count($rules) > 8 ? '...' : '');
        }
        $lines[] = "**Authorize:** " . (($req['authorize'] ?? false) ? 'Yes' : 'No');

        return implode("\n", $lines);
    }

    private function summarizePolicy(array $policy): string
    {
        $lines = [];
        $lines[] = "# {$policy['name']}";
        $lines[] = '';
        $lines[] = "**Type:** Policy | **File:** `{$policy['path']}`";
        $lines[] = "**Confidence:** 90";
        $lines[] = '';
        $lines[] = "**Purpose:** Authorization rules for `{$policy['model']}` model.";
        $lines[] = "**Abilities:** " . implode(', ', $policy['abilities'] ?? []);

        return implode("\n", $lines);
    }

    private function summarizeEvent(array $event): string
    {
        $lines = [];
        $lines[] = "# {$event['name']}";
        $lines[] = '';
        $lines[] = "**Type:** Event | **File:** `{$event['path']}`";
        $lines[] = "**Confidence:** 85";
        $lines[] = '';
        $lines[] = "**Purpose:** Signals that something happened in the application.";
        $lines[] = "**Broadcasts:** " . (($event['should_broadcast'] ?? false) ? 'Yes' : 'No');
        $lines[] = "**Queued:** " . (($event['should_queue'] ?? false) ? 'Yes' : 'No');

        return implode("\n", $lines);
    }

    private function summarizeJob(array $job): string
    {
        $lines = [];
        $lines[] = "# {$job['name']}";
        $lines[] = '';
        $lines[] = "**Type:** Job | **File:** `{$job['path']}`";
        $lines[] = "**Confidence:** 85";
        $lines[] = '';
        $lines[] = "**Purpose:** " . ($job['queued'] ? 'Async' : 'Sync') . " background task processing.";
        $lines[] = "**Queued:** " . ($job['queued'] ? 'Yes' : 'No');

        return implode("\n", $lines);
    }

    private function summarizeNotification(array $notif): string
    {
        $lines = [];
        $lines[] = "# {$notif['name']}";
        $lines[] = '';
        $lines[] = "**Type:** Notification | **File:** `{$notif['path']}`";
        $lines[] = "**Confidence:** 85";
        $lines[] = '';
        $lines[] = "**Channels:** " . implode(', ', $notif['channels'] ?? []);

        return implode("\n", $lines);
    }

    private function summarizeLivewire(array $lw): string
    {
        $lines = [];
        $lines[] = "# {$lw['name']} (Livewire)";
        $lines[] = '';
        $lines[] = "**Type:** Livewire Component";
        $lines[] = "**Confidence:** 85";
        $lines[] = '';
        $lines[] = "**View:** {$lw['view']}";
        if (!empty($lw['properties'])) $lines[] = "**Properties:** " . implode(', ', $lw['properties']);
        if (!empty($lw['computed'])) $lines[] = "**Computed:** " . implode(', ', $lw['computed']);
        if (!empty($lw['emits'])) $lines[] = "**Emits:** " . implode(', ', $lw['emits']);

        return implode("\n", $lines);
    }

    private function describeMethod(string $method, string $controllerName): string
    {
        $modelName = preg_replace('/Controller$/', '', $controllerName);
        return match ($method) {
            'index' => "List all {$modelName} records",
            'create' => "Show form to create a new {$modelName}",
            'store' => "Validate and save a new {$modelName}",
            'show' => "Display a single {$modelName}",
            'edit' => "Show form to edit a {$modelName}",
            'update' => "Validate and update an existing {$modelName}",
            'destroy' => "Delete a {$modelName} record",
            '__invoke' => "Handle single-action request",
            default => "{$method} operation",
        };
    }

    private function findServiceForController(string $ctrlName, array $data): ?string
    {
        $modelName = preg_replace('/Controller$/', '', $ctrlName);
        foreach ($data['services']['items'] ?? [] as $svc) {
            if (str_contains($svc['name'], $modelName)) return $svc['name'];
        }
        return null;
    }

    private function findRequestForController(string $ctrlName, array $data): ?string
    {
        $modelName = preg_replace('/Controller$/', '', $ctrlName);
        if (!$modelName) return null;
        foreach ($data['form_requests']['items'] ?? [] as $req) {
            if (str_contains($req['name'], $modelName)) return $req['name'];
        }
        return null;
    }
}