<?php

declare(strict_types=1);

namespace Coffesoft\LaravelBeacon\Intelligence;

/**
 * Generates architecture-report.md — a factual analysis of the project's
 * architecture style, patterns, organization, strengths, weaknesses, and
 * recommended improvements. Only uses detected facts, no subjective opinions.
 */
class ArchitectureReport
{
    /**
     * @param array<string, mixed> $data All scanned project data
     * @return array<string, mixed>
     */
    public function generate(array $data): array
    {
        $lines = [];

        $lines[] = '# Architecture Report — ' . basename(base_path());
        $lines[] = '';
        $lines[] = '> Generated by Laravel Beacon v5';
        $lines[] = '> Confidence scores (0–100) indicate reliability of each section.';
        $lines[] = '> Only detected facts are reported — no assumptions.';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        // 1. Project Style
        $lines[] = '## 1. Project Style [confidence: 90]';
        $lines[] = '';
        $arch = $data['architecture'] ?? [];
        $lines[] = "**Primary:** {$arch['primary']}";
        if (!empty($arch['secondary'])) {
            $lines[] = "**Secondary patterns:** " . implode(', ', $arch['secondary']);
        }
        $lines[] = "**Hybrid:** " . ($arch['is_hybrid'] ? 'Yes — combines multiple architectural patterns' : 'No');
        $lines[] = '';

        // 2. Architecture Patterns
        $lines[] = '---';
        $lines[] = '## 2. Detected Patterns [confidence: 85]';
        $lines[] = '';
        foreach ($arch['explanations'] ?? [] as $type => $reason) {
            $lines[] = "- **{$type}**: {$reason}";
        }
        $lines[] = '';

        // Check if Repository pattern is used
        $repos = $data['repositories']['items'] ?? [];
        $services = $data['services']['items'] ?? [];
        $hasInterface = false;
        $hasImplementation = false;
        foreach ($repos as $r) {
            if ($r['type'] === 'interface') $hasInterface = true;
            if ($r['type'] === 'implementation') $hasImplementation = true;
        }

        // 3. Folder Organization
        $lines[] = '---';
        $lines[] = '## 3. Folder Organization [confidence: 95]';
        $lines[] = '';
        $lines[] = 'The project follows standard Laravel conventions with the following detected structure:';
        $lines[] = '';

        // App structure analysis
        $appDirs = [];
        foreach (['Models', 'Http/Controllers', 'Http/Requests', 'Http/Resources', 'Http/Middleware',
                    'Services', 'Repositories', 'Policies', 'Events', 'Listeners', 'Jobs', 'Notifications',
                    'Mail', 'Traits', 'Concerns', 'Enums', 'Helpers', 'Rules', 'Livewire', 'Actions',
                    'Console/Commands', 'Exceptions', 'Providers'] as $dir) {
            if (is_dir(app_path($dir))) {
                $appDirs[] = $dir;
            }
        }

        if (!empty($appDirs)) {
            $lines[] = '**app/ directory contains:**';
            foreach ($appDirs as $dir) {
                $lines[] = "- `app/{$dir}`";
            }
        }

        // Check for Modules
        $modulesDir = base_path('Modules');
        $domainDir = app_path('../domain');
        if (is_dir($modulesDir)) {
            $lines[] = '';
            $lines[] = '**Modules detected** at `Modules/`';
            $mods = array_filter((new \FilesystemIterator($modulesDir)), fn($f) => $f->isDir());
            foreach ($mods as $mod) {
                $lines[] = "- `Modules/{$mod->getFilename()}`";
            }
        }
        if (is_dir($domainDir)) {
            $lines[] = '';
            $lines[] = '**Domain-driven structure detected** at `domain/`';
            $domains = array_filter((new \FilesystemIterator($domainDir)), fn($f) => $f->isDir());
            foreach ($domains as $dom) {
                $lines[] = "- `domain/{$dom->getFilename()}`";
            }
        }
        $lines[] = '';

        // 4. Strengths (factual)
        $strengths = [];
        $lines[] = '---';
        $lines[] = '## 4. Strengths [confidence: 80]';
        $lines[] = '';
        $lines[] = 'Based on detected patterns, the following architectural strengths are present:';
        $lines[] = '';

        if (!empty($services)) {
            $strengths[] = "Service layer: {$data['services']['count']} service classes encapsulate business logic";
        }
        if ($hasInterface && $hasImplementation) {
            $strengths[] = "Repository pattern with interfaces enables testable data access";
        }
        if (!empty($data['form_requests']['items'])) {
            $strengths[] = "Form Request validation: {$data['form_requests']['count']} request classes for clean validation";
        }
        if (!empty($data['policies']['items'])) {
            $strengths[] = "Policy-based authorization: {$data['policies']['count']} policy classes";
        }
        if (!empty($data['events']['listeners'])) {
            $strengths[] = "Event-driven architecture with listeners for decoupled side effects";
        }
        if ($data['routes']['count'] ?? 0 > 0) {
            $routeGroups = $data['route_intelligence']['groups'] ?? [];
            if (count($routeGroups) > 1) {
                $strengths[] = "Modular route organization across " . count($routeGroups) . " route groups";
            }
        }
        $crudCount = count(array_filter($data['controllers']['items'] ?? [], fn($c) => $c['is_crud'] ?? false));
        if ($crudCount > 0) {
            $strengths[] = "{$crudCount} CRUD controllers follow RESTful conventions";
        }

        foreach ($strengths as $s) {
            $lines[] = "- {$s}";
        }
        $lines[] = '';

        // 5. Potential Improvements (factual)
        $lines[] = '---';
        $lines[] = '## 5. Potential Improvements [confidence: 75]';
        $lines[] = '';
        $lines[] = 'Based on detected gaps, consider these improvements:';
        $lines[] = '';

        $hasImprovement = false;

        if (empty($services)) {
            $lines[] = "- No service layer detected — business logic may be in controllers";
            $hasImprovement = true;
        }
        if (!$hasInterface || !$hasImplementation) {
            if (!empty($repos)) {
                $lines[] = "- Repository interfaces found but no implementations, or vice versa";
                $hasImprovement = true;
            }
        }
        if (empty($data['form_requests']['items'])) {
            $lines[] = "- No Form Request classes — validation may be inline in controllers";
            $hasImprovement = true;
        }
        if (empty($data['policies']['items'])) {
            $lines[] = "- No Policy classes — authorization may be inline";
            $hasImprovement = true;
        }
        if (empty($data['events']['items'])) {
            $lines[] = "- No Event classes — consider events for decoupled processing";
            $hasImprovement = true;
        }
        if (empty($data['tests'])) {
            $testsPath = base_path('tests');
            $hasTests = is_dir($testsPath) && count(scandir($testsPath)) > 2;
            if (!$hasTests) {
                $lines[] = "- No test files detected — consider adding tests";
                $hasImprovement = true;
            }
        }

        // Check for large controllers that could be split
        $largeControllers = array_filter($data['controllers']['items'] ?? [], fn($c) => count($c['methods'] ?? []) > 10);
        if (!empty($largeControllers)) {
            $lines[] = "- Large controllers detected that could be split:";
            foreach ($largeControllers as $lc) {
                $lines[] = "  - {$lc['name']} (" . count($lc['methods'] ?? []) . " methods)";
            }
            $hasImprovement = true;
        }

        // Check for unguarded models
        $unguardedModels = [];
        foreach ($data['models']['items'] ?? [] as $m) {
            if (empty($m['fillable']) && empty($m['guarded'])) {
                $unguardedModels[] = $m['name'];
            }
        }
        if (!empty($unguardedModels)) {
            $lines[] = "- Mass assignment not explicitly configured for: " . implode(', ', $unguardedModels);
            $hasImprovement = true;
        }

        if (!$hasImprovement) {
            $lines[] = "- No significant architectural gaps detected";
        }
        $lines[] = '';

        // 6. Recommendations
        $lines[] = '---';
        $lines[] = '## 6. Recommendations';
        $lines[] = '';
        $lines[] = 'Based on the project\'s detected architecture:';
        $lines[] = '';

        $patterns = $arch['secondary'] ?? [];
        if (in_array('Repository Pattern', $patterns)) {
            $lines[] = '- **Repository layer**: Maintain consistent use of repositories across all models';
        }
        if (in_array('Service Layer', $patterns) || !empty($services)) {
            $lines[] = '- **Service layer**: Keep business logic in services, controllers thin';
        }
        if (count($data['controllers']['items'] ?? []) > 20) {
            $lines[] = '- **Organization**: Consider grouping controllers by feature/module';
        }
        if (!empty($data['policies']['items'])) {
            $lines[] = '- **Authorization**: Use policies consistently; register in AuthServiceProvider';
        }
        if (!empty($data['jobs']['items'])) {
            $lines[] = '- **Queue**: Consider Horizon for queue monitoring if using Redis';
        }

        $lines[] = '';

        return [
            'architecture_report' => [
                'content' => implode("\n", $lines),
                'line_count' => substr_count(implode("\n", $lines), "\n") + 1,
                'confidence' => 80,
            ],
        ];
    }
}