<?php

declare(strict_types=1);

namespace Coffesoft\LaravelBeacon\Exporter;

use Coffesoft\LaravelBeacon\Context\Context;
use Illuminate\Support\Facades\File;

/**
 * Exports Context to a clean, AI-ready markdown file.
 */
class MarkdownExporter
{
    /**
     * Export context to markdown file.
     */
    public function export(Context $context, string $outputPath): string
    {
        $markdown = $this->build($context);

        File::ensureDirectoryExists(dirname($outputPath));
        File::put($outputPath, $markdown);

        return $outputPath;
    }

    /**
     * Build markdown content from context.
     */
    public function build(Context $context): string
    {
        $lines = [];

        $lines[] = '# Laravel Project Context';
        $lines[] = '';
        $lines[] = '> **Generated:** ' . $context->get('generated_at', 'N/A');
        $lines[] = '> **Tool:** Laravel Beacon';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        $this->addProjectOverview($lines, $context);
        $this->addArchitecture($lines, $context);
        $this->addModels($lines, $context);
        $this->addControllers($lines, $context);
        $this->addRoutes($lines, $context);
        $this->addMigrations($lines, $context);

        $lines[] = '---';
        $lines[] = '';
        $lines[] = '*Generated by Laravel Beacon — Project Context Generator*';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function addProjectOverview(array &$lines, Context $context): void
    {
        $fw = $context->get('framework', []);

        $lines[] = '## 1. Project Overview';
        $lines[] = '';
        $lines[] = '| Metric | Value |';
        $lines[] = '|---|---|';
        $lines[] = '| Framework | ' . ($fw['name'] ?? 'Laravel') . ' ' . ($fw['version'] ?? '') . ' |';
        $lines[] = '| PHP Version | ' . ($fw['php_version'] ?? 'N/A') . ' |';
        $lines[] = '| Models | ' . $context->get('models.count', 0) . ' |';
        $lines[] = '| Controllers | ' . $context->get('controllers.count', 0) . ' |';
        $lines[] = '| Routes | ' . $context->get('routes.count', 0) . ' |';
        $lines[] = '| Migrations | ' . $context->get('migrations.count', 0) . ' |';
        $lines[] = '';
    }

    private function addArchitecture(array &$lines, Context $context): void
    {
        $modules = $context->get('modules.modules', []);

        $lines[] = '## 2. Architecture';
        $lines[] = '';

        if (empty($modules)) {
            $lines[] = 'No modules detected.';
            $lines[] = '';
            return;
        }

        $lines[] = '| Module | Routes |';
        $lines[] = '|---|---|';

        foreach ($modules as $module) {
            $lines[] = '| ' . $module['label'] . ' | ' . $module['route_count'] . ' |';
        }

        $lines[] = '';
    }

    private function addModels(array &$lines, Context $context): void
    {
        $items = $context->get('models.items', []);

        $lines[] = '## 3. Models';
        $lines[] = '';

        if (empty($items)) {
            $lines[] = 'No models detected.';
            $lines[] = '';
            return;
        }

        foreach ($items as $model) {
            $lines[] = '### ' . $model['name'];
            $lines[] = '';
            $lines[] = '- **Namespace:** `' . $model['namespace'] . '`';
            $lines[] = '- **Path:** `' . $model['path'] . '`';

            $relations = $model['relations'] ?? [];
            if (! empty($relations)) {
                $lines[] = '- **Relationships:**';
                foreach ($relations as $type => $count) {
                    $lines[] = '  - ' . $type . ': ' . $count;
                }
            }

            $fillable = $model['fillable'] ?? [];
            if (! empty($fillable)) {
                $lines[] = '- **Fillable:** `' . implode('`, `', $fillable) . '`';
            }

            $lines[] = '';
        }
    }

    private function addControllers(array &$lines, Context $context): void
    {
        $items = $context->get('controllers.items', []);

        $lines[] = '## 4. Controllers';
        $lines[] = '';

        if (empty($items)) {
            $lines[] = 'No controllers detected.';
            $lines[] = '';
            return;
        }

        $groups = [];
        foreach ($items as $c) {
            $group = $c['group'] ?? 'root';
            $groups[$group][] = $c;
        }

        foreach ($groups as $group => $controllers) {
            $lines[] = '### Group: `' . $group . '`';
            $lines[] = '';
            $lines[] = '| Controller | Methods |';
            $lines[] = '|---|---|';

            foreach ($controllers as $c) {
                $methods = implode(', ', array_slice($c['methods'] ?? [], 0, 10));
                if (count($c['methods'] ?? []) > 10) {
                    $methods .= ', ...';
                }
                $lines[] = '| ' . $c['name'] . ' | `' . $methods . '` |';
            }

            $lines[] = '';
        }
    }

    private function addRoutes(array &$lines, Context $context): void
    {
        $groups = $context->get('routes.groups', []);

        $lines[] = '## 5. Routes';
        $lines[] = '';

        if (empty($groups)) {
            $lines[] = 'No routes detected.';
            $lines[] = '';
            return;
        }

        $lines[] = '| Group | Count |';
        $lines[] = '|---|---|';

        foreach ($groups as $prefix => $count) {
            $lines[] = '| `' . $prefix . '` | ' . $count . ' |';
        }

        $lines[] = '';
    }

    private function addMigrations(array &$lines, Context $context): void
    {
        $items = $context->get('migrations.items', []);
        $tables = $context->get('migrations.tables', []);

        $lines[] = '## 6. Migrations';
        $lines[] = '';

        if (! empty($tables)) {
            $lines[] = '| Table |';
            $lines[] = '|---|---|';
            foreach ($tables as $table) {
                $lines[] = '| `' . $table . '` |';
            }
            $lines[] = '';
            $lines[] = 'Total: ' . count($items) . ' migration files, ' . count($tables) . ' tables.';
        } else {
            $lines[] = 'No migrations detected.';
        }

        $lines[] = '';
    }
}