<?php

declare(strict_types=1);

namespace Coffesoft\LaravelBeacon\Console;

use Coffesoft\LaravelBeacon\Builder\ContextBuilder;
use Coffesoft\LaravelBeacon\Intelligence\ReviewEngine;
use Illuminate\Console\Command;

class BeaconReviewCommand extends Command
{
    protected $signature = 'beacon:review
                            {--output= : Output directory (default: storage/app/beacon)}
                            {--min-severity=info : Minimum severity level (info, warning, high, critical)}
                            {--format=both : Output format: md, json, both}';

    protected $description = 'Analyze project code quality and generate AI review report';

    public function __construct(
        private readonly ContextBuilder $builder,
        private readonly ReviewEngine $reviewEngine,
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $this->newLine();
        $this->info(' 🔍 Beacon Review — AI Code Quality Analysis');
        $this->line(' ───────────────────────────────────────────');
        $this->newLine();

        // Scan project
        $this->warn(' Scanning project...');
        $context = $this->builder->build();
        $data = $context->all();
        $this->info(' ✓ Project scanned');

        // Review
        $this->newLine();
        $this->warn(' Analyzing code quality...');
        $result = $this->reviewEngine->analyze($data);
        $this->info(' ✓ Analysis complete');
        $this->newLine();

        $review = $result['review'];
        $findings = $review['findings'] ?? [];
        $summary = $review['summary'] ?? [];
        $minSeverity = $this->option('min-severity');

        // Filter by severity
        $severityLevels = ['info' => 0, 'warning' => 1, 'high' => 2, 'critical' => 3];
        $minLevel = $severityLevels[$minSeverity] ?? 0;
        $filteredFindings = array_filter($findings, fn($f) => ($severityLevels[$f['severity']] ?? 0) >= $minLevel);

        // Summary table
        $this->table(
            ['Severity', 'Count'],
            [
                ['🔴 Critical', $summary['critical'] ?? 0],
                ['🟠 High', $summary['high'] ?? 0],
                ['🟡 Warning', $summary['warning'] ?? 0],
                ['🔵 Info', $summary['info'] ?? 0],
            ]
        );
        $this->newLine();

        // Show findings
        foreach ($filteredFindings as $finding) {
            $icon = match ($finding['severity']) {
                'critical' => '🔴',
                'high' => '🟠',
                'warning' => '🟡',
                default => '🔵',
            };
            $confidence = $finding['confidence'] ?? 0;
            $this->line(" {$icon} [{$finding['severity']}] (confidence: {$confidence}%) {$finding['message']}");
            if (!empty($finding['suggested_fix'])) {
                $this->line("    💡 Fix: {$finding['suggested_fix']}");
            }
        }

        if (empty($filteredFindings)) {
            $this->info(' 🎉 No issues found at the specified severity level!');
        }
        $this->newLine();

        // Export
        $outputDir = $this->option('output') ?? storage_path('app/beacon');
        if (!is_dir($outputDir)) mkdir($outputDir, 0755, true);

        $format = $this->option('format');

        // Generate markdown
        if ($format === 'md' || $format === 'both') {
            $md = $this->buildMarkdown($filteredFindings, $summary);
            $mdPath = $outputDir . '/review.md';
            file_put_contents($mdPath, $md);
            $this->line("   ✓ review.md -> " . $this->shortPath($mdPath));
        }
        if ($format === 'json' || $format === 'both') {
            $jsonPath = $outputDir . '/review.json';
            file_put_contents(
                $jsonPath,
                json_encode(['findings' => array_values($filteredFindings), 'summary' => $summary], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
            );
            $this->line("   ✓ review.json -> " . $this->shortPath($jsonPath));
        }

        $this->newLine();
        $this->info(' ✅ Review complete!');

        return self::SUCCESS;
    }

    private function buildMarkdown(array $findings, array $summary): string
    {
        $lines = [];
        $lines[] = '# Beacon Code Review Report';
        $lines[] = '';
        $lines[] = '> Generated by Laravel Beacon v5 — AI Working Context';
        $lines[] = '> Severity: 🔴 Critical, 🟠 High, 🟡 Warning, 🔵 Info';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        $lines[] = '## Summary';
        $lines[] = '';
        $lines[] = "| Severity | Count |";
        $lines[] = "|---------|-------|";
        $lines[] = "| 🔴 Critical | {$summary['critical']} |";
        $lines[] = "| 🟠 High | {$summary['high']} |";
        $lines[] = "| 🟡 Warning | {$summary['warning']} |";
        $lines[] = "| 🔵 Info | {$summary['info']} |";
        $lines[] = "| **Total** | **" . count($findings) . "** |";
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        foreach ($findings as $finding) {
            $icon = match ($finding['severity']) {
                'critical' => '🔴', 'high' => '🟠', 'warning' => '🟡', default => '🔵',
            };
            $lines[] = "### {$icon} {$finding['type']} ({$finding['severity']})";
            $lines[] = '';
            $lines[] = "**Message:** {$finding['message']}";
            $lines[] = "**Confidence:** {$finding['confidence']}%";
            if (!empty($finding['class'])) $lines[] = "**Class:** `{$finding['class']}`";
            if (!empty($finding['path'])) $lines[] = "**File:** `{$finding['path']}`";
            if (!empty($finding['metric'])) $lines[] = "**Metric:** {$finding['metric']}" . (isset($finding['threshold']) ? " (threshold: {$finding['threshold']})" : '');
            if (!empty($finding['suggested_fix'])) $lines[] = "**Suggested Fix:** {$finding['suggested_fix']}";
            if (!empty($finding['affected'])) $lines[] = "**Affected:** " . implode(', ', $finding['affected']);
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function shortPath(string $path): string
    {
        $base = base_path();
        return str_starts_with($path, $base) ? substr($path, strlen($base) + 1) : $path;
    }
}