<?php

declare(strict_types=1);

namespace Coffesoft\LaravelBeacon\Console;

use Coffesoft\LaravelBeacon\Builder\ContextBuilder;
use Coffesoft\LaravelBeacon\Intelligence\RouteHealthEngine;
use Illuminate\Console\Command;

class BeaconRouteHealthCommand extends Command
{
    protected $signature = 'beacon:route-health
                            {--output= : Output directory (default: storage/app/beacon)}
                            {--format=both : Output format: md, json, both}';

    protected $description = 'Analyze all routes for quality, duplicates, and orphan issues';

    public function __construct(
        private readonly ContextBuilder $builder,
        private readonly RouteHealthEngine $routeHealth,
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $this->newLine();
        $this->info(' 🛣️ Beacon Route Health — Route Quality Analysis');
        $this->line(' ────────────────────────────────────────────────');
        $this->newLine();

        $this->warn(' Scanning project...');
        $context = $this->builder->build();
        $data = $context->all();
        $this->info(' ✓ Project scanned');

        $this->newLine();
        $this->warn(' Analyzing routes...');
        $result = $this->routeHealth->analyze($data);
        $health = $result['route_health'];
        $this->info(' ✓ Analysis complete');
        $this->newLine();

        $this->table(
            ['Metric', 'Value'],
            [
                ['Total Routes', $health['total_routes']],
                ['Issues Found', $health['issues_count']],
                ['Method Breakdown', $this->methodBreakdownString($health['method_breakdown'] ?? [])],
            ]
        );
        $this->newLine();

        foreach ($health['issues'] ?? [] as $issue) {
            $icon = match ($issue['severity']) { 'high' => '🟠', 'warning' => '🟡', default => '🔵' };
            $this->line(" {$icon} [{$issue['severity']}] {$issue['message']} (confidence: {$issue['confidence']}%)");
            if (!empty($issue['suggested_fix'])) {
                $this->line("    💡 {$issue['suggested_fix']}");
            }
        }

        if (empty($health['issues'])) {
            $this->info(' 🎉 No route issues detected!');
        }
        $this->newLine();

        // Export
        $outputDir = $this->option('output') ?? storage_path('app/beacon');
        if (!is_dir($outputDir)) mkdir($outputDir, 0755, true);
        $format = $this->option('format');

        if ($format === 'md' || $format === 'both') {
            $mdPath = $outputDir . '/route-health.md';
            file_put_contents($mdPath, $this->buildMarkdown($health));
            $this->line("   ✓ route-health.md");
        }
        if ($format === 'json' || $format === 'both') {
            $jsonPath = $outputDir . '/route-health.json';
            file_put_contents($jsonPath, json_encode($health, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
            $this->line("   ✓ route-health.json");
        }

        $this->newLine();
        $this->info(' ✅ Route health check complete!');

        return self::SUCCESS;
    }

    private function methodBreakdownString(array $breakdown): string
    {
        $parts = [];
        foreach (['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as $m) {
            if (isset($breakdown[$m])) $parts[] = "{$m}: {$breakdown[$m]}";
        }
        return implode(', ', $parts);
    }

    private function buildMarkdown(array $health): string
    {
        $md = [];
        $md[] = '# Route Health Report';
        $md[] = '';
        $md[] = '> Generated by Laravel Beacon v5.0';
        $md[] = '';
        $md[] = '---';
        $md[] = '';

        $md[] = '## Summary';
        $md[] = '';
        $md[] = "| Metric | Value |";
        $md[] = "|--------|-------|";
        $md[] = "| Total Routes | {$health['total_routes']} |";
        $md[] = "| Issues Found | {$health['issues_count']} |";
        $md[] = '';

        $breakdown = $health['method_breakdown'] ?? [];
        if (!empty($breakdown)) {
            $md[] = '## Method Breakdown';
            $md[] = '';
            $md[] = '| Method | Count |';
            $md[] = '|--------|-------|';
            foreach (['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as $m) {
                if (isset($breakdown[$m])) $md[] = "| {$m} | {$breakdown[$m]} |";
            }
            $md[] = '';
        }

        foreach ($health['issues'] ?? [] as $issue) {
            $md[] = '---';
            $md[] = "## {$issue['type']} (confidence: {$issue['confidence']}%)";
            $md[] = '';
            $md[] = "{$issue['message']}";
            $md[] = '';
            if (!empty($issue['routes'])) {
                $md[] = 'Affected routes:';
                foreach ($issue['routes'] as $r) $md[] = "- `{$r}`";
                $md[] = '';
            }
            if (!empty($issue['suggested_fix'])) {
                $md[] = "**Suggested fix:** {$issue['suggested_fix']}";
                $md[] = '';
            }
        }

        return implode("\n", $md);
    }
}